### ISSUE TITLE
Remarques gérénales

### ISSUE THREAD

**Issue by Pierre-Loic** [silky55/Projet5#2]
Supprimer les dossiers .vs et __pycache__ du repository

**Comment by Pierre-Loic** [comment]
Pour toutes les mises à jour de code suite à des "Issues", mettre en lien le # de l'issue pour la traçabilité

**Comment by Pierre-Loic** [comment]
Supprimer l'affichage en console des messages de debug pour l'utilisateur

**Comment by Pierre-Loic** [comment]
Supprimer les commentaires utilisés pour tester du code
https://github.com/julienbassin/Projet5/blob/bfeca05cd9d4c9e7278770dfb32b0f75f2863637/openfoodfacts_requests.py#L40

**Comment by 8ee9627a76dab2c8a7** [comment]
> Supprimer les dossiers .vs et **pycache** du repository

Pris en compte.
