### ISSUE TITLE
Fichier requirements.txt  à mettre à jour

### ISSUE THREAD

**Issue by Pierre-Loic** [silky55/Projet5#5]
https://github.com/julienbassin/Projet5/blob/bfeca05cd9d4c9e7278770dfb32b0f75f2863637/openfoodfacts_bdd.py#L4
la librairie n'est pas dans le fichier requirements.txt

**Comment by 8ee9627a76dab2c8a7** [comment]
Changement pris en compte

**Comment by Pierre-Loic** [comment]
Dans quel commit?
