### ISSUE TITLE
Problème de connexion à la BDD

### ISSUE THREAD

**Issue by Pierre-Loic** [silky55/Projet5#6]
sqlalchemy.exc.DatabaseError: (mysql.connector.errors.DatabaseError) 2003 (HY000): Can't connect to MySQL server on 'localhost' (10061)

**Comment by 8ee9627a76dab2c8a7** [comment]
https://stackoverflow.com/questions/1673530/error-2003-hy000-cant-connect-to-mysql-server-on-127-0-0-1-111
